### PR TITLE
Add a note on security against quantum attacks

### PR DESCRIPTION
**Pull request by jedisct1**
https://eprint.iacr.org/2023/1306.pdf analyses the security of AEGIS-128L and other ciphers in the Q2 model (which is highly impractical), but also mentions that all the schemes are secure in the Q1 model.

### CODE REVIEW

**Review by samuel-lucas6 — APPROVED** [review]
Not related to this PR, but should we remove `in Chapter 4 of` so there only needs to be one `in` within this sentence:

> Security analyses of AEGIS can be found in {{AEGIS}}, {{M14}}, {{ENP19}}, {{LIMS21}}, {{JLD21}}, {{STSI23}}, {{IR23}}, and {{BS23}}.

**Comment by jedisct1** [comment]
How about moving "and in Chapter 4 of {{AEGIS}}" to the end?

**Comment by samuel-lucas6** [comment]
> How about moving "and in Chapter 4 of {{AEGIS}}" to the end?

That works too, although it's no longer in order of publication. I'll leave it up to you.

**Comment by jedisct1** [comment]
Having these in order of publication is good. Let's just remove "in chapter 4", then.

**Comment by samuel-lucas6** [comment]
> Having these in order of publication is good. Let's just remove "in chapter 4", then.

Do you want to keep the other `in`s? Because if not, you forgot to remove them :p Otherwise, feel free to merge.

**Comment by jedisct1** [comment]
Better without the redundant "in"s !

**Pull request merged**
