### PR TITLE
Fix off-by-one in P_MAX and A_MAX

### LINKED ISSUE #45: spec: Off-by-one error in the definition of RFC 5116 constants
[RFC 5116](https://www.rfc-editor.org/rfc/rfc5116) defines `A_MAX` and `P_MAX` as an inclusive range (Section 4)

> Each AEAD algorithm MUST accept any plaintext with a length between
> zero and P_MAX octets, inclusive, where the value P_MAX is specific
> to that algorithm.

> Each AEAD algorithm MUST accept any associated data with a length
> between zero and A_MAX octets, inclusive, where the value A_MAX is
> specific to that algorithm.

The draft algorithm high-level definitions appear to follow this convention (Section 3, 4):

https://github.com/cfrg/draft-irtf-cfrg-aegis-aead/blob/dc1f4805eba4c4305b16f9741524dbde0ccea586/draft-irtf-cfrg-aegis-aead.md?plain=1#L362-L363

https://github.com/cfrg/draft-irtf-cfrg-aegis-aead/blob/dc1f4805eba4c4305b16f9741524dbde0ccea586/draft-irtf-cfrg-aegis-aead.md?plain=1#L698-L699

However, it is clear from the algorithm pseduocode sections and how the tag is generated that this P_MAX/A_MAX must be exclusive (Links to the AEGIS-256 copies omitted for brevity).

https://github.com/cfrg/draft-irtf-cfrg-aegis-aead/blob/dc1f4805eba4c4305b16f9741524dbde0ccea586/draft-irtf-cfrg-aegis-aead.md?plain=1#L385-L386

https://github.com/cfrg/draft-irtf-cfrg-aegis-aead/blob/dc1f4805eba4c4305b16f9741524dbde0ccea586/draft-irtf-cfrg-aegis-aead.md?plain=1#L679

While it is a combination of impossible/impractical/unlikely that data will every reach the length where this discrepancy actually matters, `P_MAX` and `A_MAX` should be changed to be `2^61 - 1 bytes (2^64 - 8 bits)`, and `C_MAX` should be updated accordingly.

### PR DESCRIPTION
**Pull request by jedisct1**
Spotted by @Yawning, thanks!

Fixes #45

### CODE REVIEW

**Comment by Yawning** [comment]
No problem.

The AEGIS-256 description also has the issue, so one more place to update.

https://github.com/cfrg/draft-irtf-cfrg-aegis-aead/blob/9cccd938bb387ca9f643d438b2b139a073b3bc8a/draft-irtf-cfrg-aegis-aead.md?plain=1#L698-L701

**Review by samuel-lucas6 — COMMENTED** [review]
Shouldn't `length MUST be less than P_MAX` and `length MUST be less than A_MAX` (in Section 3.1 and 4.1) still be changed? Otherwise, the maximum is technically 2<sup>61</sup> - 2 bytes.

If I'm right about that, `length MUST be less than C_MAX` and `length MUST be less than A_MAX` should also be changed in Section 3.2 and 4.2.

Besides that, it looks ok. I'm not super keen on the brackets inside brackets, but there's not really anything you can do.

**Comment by Yawning** [comment]
> Shouldn't `length MUST be less than P_MAX` and `length MUST be less than A_MAX` (in Section 3.1 and 4.1) still be changed? Otherwise, the maximum is technically 261 - 2 bytes.
> 
> If I'm right about that, `length MUST be less than C_MAX` and `length MUST be less than A_MAX` should also be changed in Section 3.2 and 4.2.

Ah, yes.  That's right.

Unrelated, thanks for the nice spec, I've been working on implementing 128L and 256, and it's been easy to do.

**Comment by jedisct1** [comment]
Good catch, @samuel-lucas6 !

**Review by samuel-lucas6 — APPROVED** [review]
LGTM. Thanks @Yawning!

**Pull request merged**
